gpu_id: 0
load_csi_prediction_checkpoint: 'checkpoints/Umi_outdoor30/csi_prediction_latest'
lr_net: 5e-4
train_epoch: 500
only_test: False

dataset:
  batch_size: 2280
  total_data: True
  data_split_flag: True
  data_split: '9:1:0'
  dataroot: 'dataset'
  dataroot_x: '/data/lzh/Umi_outdoor30_1_6_11_16(5).mat'
  dataroot_y: '/data/lzh/Umi_outdoor30_21(5).mat'
  data_setting: 0
module:
  loss:
    l2_lambda : 0.0
    mse_lambda : 1.0
    sgcs_lambda : 1.0
  model_name: 'TransLSTM'
  ConvLSTM:
    convlstm_layer: 2
    CNN_layer: 3
    convlstm_input_dim: [4, 64]
    convlstm_output_dim: [64, 128]
    convlstm_kernel_size: [3, 5]
    CNN_input_dim: [128, 128, 64]
    CNN_output_dim: [128, 64, 64]
    CNN_kernel_size: [3, 3, 3]
    CNN_stride: [2, 2, 1]
  TransLSTM:
    trans_layers_num: 6
    d_model: 512
    d_ff: 2048
    h: 8
    dropout: 0.1
    lstm_layers_num: 6
recorder:
  name: 'csi_prediction'
  logdir: 'log/csi_prediction'
  checkpoint_path: 'checkpoints'
  result_path: 'results'
  comment: 'long_epoch'
  save_total_cfg: True
  save_freq: 4000
