gpu_id: 0
load_csi_prediction_checkpoint: 'checkpoints/Umi_outdoor30/csi_prediction_latest'
lr_net: 1e-4
train_epoch: 300
only_test: False

dataset:
  batch_size: 1140
  total_data: True
  data_split_flag: True
  data_split: '7:3:0'
  dataroot: 'dataset'
  dataroot_x: 'dataset/Umi_outdoor30_1_6_11_16(5).mat'
  dataroot_y: 'dataset/Umi_outdoor30_21(5).mat'

module:
  model_name: 'ConvLSTM'
  ConvLSTM:
    l2_lambda : 0.0
    mse_lambda : 1.0
    sgcs_lambda : 1.0

recorder:
  name: 'csi_prediction'
  logdir: 'log/csi_prediction'
  checkpoint_path: 'checkpoints'
  result_path: 'results'
  comment: 'debug'
  save_total_cfg: True
  save_freq: 2000
