gpu_id: 0
load_csi_prediction_checkpoint: 'checkpoints/Umi_outdoor30/csi_prediction_latest'
load_gaussianhead_checkpoint: 'checkpoints/gaussianhead_NeRSemble031/gaussianhead_latest'
load_supres_checkpoint: 'checkpoints/gaussianhead_NeRSemble031/supres_latest'
load_delta_poses_checkpoint: 'checkpoints/gaussianhead_NeRSemble031/delta_poses_latest'
lr_net: 1e-4
lr_pose: 1e-5
batch_size: 4
optimize_pose: True

dataset:
  total_data: False
  data_split_flag: True
  data_split: '8:2:0'
  dataroot: 'dataset'
  dataroot_x: 'dataset/Umi_outdoor30_1_6_11_16(5).mat'
  dataroot_y: 'dataset/Umi_outdoor30_21(5).mat'
  
module:
  name: 'ConvLSTM'
meshheadmodule:
  geo_mlp: [27, 256, 256, 256, 256, 256, 132]
  exp_color_mlp: [192, 256, 256, 32]
  pose_color_mlp: [182, 128, 32]
  exp_deform_mlp: [91, 256, 256, 256, 256, 256, 3]
  pose_deform_mlp: [81, 256, 256, 3]
  pos_freq: 4
  model_bbox: [[-1.6, 1.6], [-1.7, 1.8], [-2.5, 1.0]]
  dist_threshold_near: 0.1
  dist_threshold_far: 0.25
  deform_scale: 0.3
  subdivide: False

supresmodule:
  input_dim: 32
  output_dim: 3
  network_capacity: 32

gaussianheadmodule:
  num_add_mouth_points: 3000
  exp_color_mlp: [192, 256, 256, 32]
  pose_color_mlp: [182, 128, 32]
  exp_deform_mlp: [91, 256, 256, 256, 256, 256, 3]
  pose_deform_mlp: [81, 256, 256, 3]
  exp_attributes_mlp: [192, 256, 256, 256, 8]
  pose_attributes_mlp: [182, 128, 128, 8]
  exp_coeffs_dim: 64
  pos_freq: 4
  dist_threshold_near: 0.1
  dist_threshold_far: 0.25
  deform_scale: 0.3
  attributes_scale: 0.2

recorder:
  name: 'gaussianhead_NeRSemble031'
  logdir: 'log/gaussianhead_NeRSemble031'
  checkpoint_path: 'checkpoints'
  result_path: 'results'
  save_freq: 1000
  show_freq: 100