gpu_id: 0
load_csi_prediction_checkpoint: 'checkpoints/Umi_outdoor30/csi_prediction_latest'
lr_net: 1e-4
batch_size: 1024
train_epoch: 10
optimize_pose: True

dataset:
  total_data: False
  data_split_flag: True
  data_split: '8:2:0'
  dataroot: 'dataset'
  dataroot_x: 'dataset/Umi_outdoor30_1_6_11_16(5).mat'
  dataroot_y: 'dataset/Umi_outdoor30_21(5).mat'
  
module:
  name: 'ConvLSTM'


recorder:
  name: 'csi_prediction'
  logdir: 'log/csi_prediction'
  checkpoint_path: 'checkpoints'
  result_path: 'results'
  save_freq: 50
